name: studhue_draft
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - graphics/Background.png
    - graphics/Logo 2 A.png
    - graphics/Logo B.png
    - graphics/Logo C.png
    - graphics/back_button.png
    - graphics/Typography.png
    - graphics/Back Button.png
    - graphics/Chat.png
    - graphics/Comment.png
    - graphics/Dots.png
    - graphics/Heart.png
    - graphics/Mic.png
    - graphics/Notification.png
    - graphics/Pin.png
    - graphics/Profile Icon.png
    - graphics/Search Button.png
    - graphics/Top Nav Bar.png
    - graphics/Vault Button.png
    - graphics/Verified Icon.png
    - graphics/Homeheader.png
    - graphics/feed posts/fpost1.jpg
    - graphics/feed posts/fpost2.jpg
    - graphics/feed posts/fpost3.jpg
    - graphics/feed posts/fpost4.jpg
    - graphics/profile posts/post1.jpg
    - graphics/profile posts/post2.jpg
    - graphics/profile posts/post3.jpg
    - graphics/profile posts/post4.jpg
    - graphics/profile posts/post5.jpg
    - graphics/profile posts/post6.jpg
    - graphics/profile posts/post7.jpg
    - graphics/profile posts/post8.jpg
    - graphics/profile posts/post9.jpg
    - graphics/icons/icon1.jpg
    - graphics/icons/icon2.jpg
    - graphics/icons/icon3.jpg
    - graphics/icons/icon4.jpg
    - graphics/icons/icon5.jpg
    - graphics/icons/icon6.jpg
    - graphics/icons/icon7.jpg
    - graphics/icons/icon8.jpg
    - graphics/icons/icon9.jpg
    - graphics/icons/icon10.jpg
    - graphics/icons/icon11.jpg
    - graphics/products/product1.jpg
    - graphics/products/product2.jpg
    - graphics/products/product3.jpg
    - graphics/products/product4.jpg
    - graphics/products/product5.jpg
    - graphics/products/product6.jpg
    - graphics/products/product7.jpg
    - graphics/pinboard/pin1.jpg
    - graphics/pinboard/pin2.jpg
    - graphics/pinboard/pin3.jpg
    - graphics/pinboard/pin4.jpg
    - graphics/pinboard/pin5.jpg
    - graphics/pinboard/pin6.jpg
    - graphics/pinboard/pin7.jpg
    - graphics/pinboard/pin8.jpg
    - graphics/pinboard/pin9.jpg
    - graphics/pinboard/pin10.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
